apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aks-developer-rolebinding
  namespace: app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aks-developer-role
subjects:
  - kind: Group
    namespace: app
    name: e4a722dd-4295-411a-a555-7e41410ef805