name: Bors Runs

on:
  push:
    branches:
      - main
      - features

jobs:
  test:
    name: Bors
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - uses: hashicorp/setup-terraform@v2
      - run: terraform init

        