name: Bors Runs

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - uses: hashicorp/setup-terraform@v2
      - run: terraform init

    done:
    name: Done
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Done
        run: echo Done

        