name: manage-azure-policy-9fcf5a05
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/policies/Deny_PrivateEndpoint_PrivateLink_Service_Connections_Deny-PE-cross-tenant/**'
#      - 'policies/policies/PostgreSQL_database_servers_enforce_SSL_connection._Deny-PostgreSql-http/**'
#      - 'policies/policies/Deny_the_creation_of_private_DNS_Deny-Private-DNS-Zones/**'
#      - 'policies/policies/Public_network_access_should_be_disabled_for_MariaDB_Deny-PublicEndpoint-MariaDB/**'
#      - 'policies/policies/Deny_the_creation_of_public_IP_Deny-PublicIP/**'
#      - 'policies/policies/Deny_Storage_PrivateEndpoint_Connections_Deny-Storage-PEConn/**'
#      - 'policies/policies/Deny_vNet_peering_Deny-VNet-Peering/**'
#      - 'policies/policies/Deny_vNet_peering_cross_subscription._Deny-VNET-Peer-Cross-Sub/**'
#      - 'policies/policies/MySQL_database_servers_enforce_SSL_connections._Deny-MySql-http/**'
#      - 'policies/policies/Deny_PrivateEndpoint_PrivateLink_Service_Connections_Deny-PE-cross-tenant/**'
#      - 'policies/policies/PostgreSQL_database_servers_enforce_SSL_connection._Deny-PostgreSql-http/**'
#      - 'policies/policies/Prevent_cross_subscription_Private_Link_Deny-plink-cross-Sub/**'
#      - 'policies/policies/Deny_the_creation_of_private_DNS_Deny-Private-DNS-Zones/**'
#      - 'policies/policies/Public_network_access_should_be_disabled_for_MariaDB_Deny-PublicEndpoint-MariaDB/**'
#      - 'policies/policies/Deny_the_creation_of_public_IP_Deny-PublicIP/**'
#      - 'policies/policies/Deny_vNet_peering_Deny-VNet-Peering/**'
#      - 'policies/policies/Deny_vNet_peering_cross_subscription._Deny-VNET-Peer-Cross-Sub/**'
#      - 'policies/policies/Deny_Storage_PrivateEndpoint_Connections_Deny-Storage-PEConn/**'
#      - 'policies/policies/Storage_Account_set_to_minumum_TLS_and_Secure_transfer_should_be_enabled_Deny-Storage-minTLS/**'
#      - 'policies/policies/SQL_Managed_Instance_should_have_the_minimal_TLS_version_set_to_the_highest_version_Deny-SqlMi-minTLS/**'
#      - 'policies/policies/Azure_SQL_Database_should_have_the_minimal_TLS_version_set_to_the_highest_version_Deny-Sql-minTLS/**'
#      - 'policies/policies/Azure_Cache_for_Redis_only_secure_connections_should_be_enabled_Deny-Redis-http/**'
#      - 'policies/policies/Storage_accounts_should_be_have_minimal_TLS_version_1.2_Deny-storage-tls-lt1-2/**'
#      - 'policies/policies/Storage_accounts_should_be_have_minimal_TLS_version_1.2_Deny-storage-tls-lt1-2/**'
#      - 'policies/policies/Azure_SQL_Database_should_have_the_minimal_TLS_version_set_to_the_highest_version_Deny-Sql-minTLS/**'
#      - 'policies/policies/SQL_Managed_Instance_should_have_the_minimal_TLS_version_set_to_the_highest_version_Deny-SqlMi-minTLS/**'
#      - 'policies/policies/Storage_Account_set_to_minumum_TLS_and_Secure_transfer_should_be_enabled_Deny-Storage-minTLS/**'
#      - 'policies/policies/RDP_access_from_the_Internet_should_be_blocked_Deny-RDP-From-Internet/**'
#      - 'policies/policies/Prevent_cross_subscription_Private_Link_Deny-plink-cross-Sub/**'
#      - 'policies/policies/MySQL_database_servers_enforce_SSL_connections._Deny-MySql-http/**'
#      - 'policies/policies/Application_Gateway_should_be_deployed_with_WAF_enabled_Deny-AppGW-Without-WAF/**'
#      - 'policies/policies/Web_Application_should_only_be_accessible_over_HTTPS_Deny-AppServiceWebApp-http/**'
#      - 'policies/policies/Function_App_should_only_be_accessible_over_HTTPS_Deny-AppServiceFunctionApp-http/**'
#      - 'policies/policies/API_App_should_only_be_accessible_over_HTTPS_Deny-AppServiceApiApp-http/**'
#      - 'policies/policies/Azure_Cache_for_Redis_only_secure_connections_should_be_enabled_Deny-Redis-http/**'
#      - 'policies/policies/Function_App_should_only_be_accessible_over_HTTPS_Deny-AppServiceFunctionApp-http/**'
#      - 'policies/policies/API_App_should_only_be_accessible_over_HTTPS_Deny-AppServiceApiApp-http/**'
#      - 'policies/policies/Web_Application_should_only_be_accessible_over_HTTPS_Deny-AppServiceWebApp-http/**'
#      - .github/workflows/manage-azure-policy-9fcf5a05.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_9fcf5a05}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/policies/Deny_PrivateEndpoint_PrivateLink_Service_Connections_Deny-PE-cross-tenant/**
          policies/policies/PostgreSQL_database_servers_enforce_SSL_connection._Deny-PostgreSql-http/**
          policies/policies/Deny_the_creation_of_private_DNS_Deny-Private-DNS-Zones/**
          policies/policies/Public_network_access_should_be_disabled_for_MariaDB_Deny-PublicEndpoint-MariaDB/**
          policies/policies/Deny_the_creation_of_public_IP_Deny-PublicIP/**
          policies/policies/Deny_Storage_PrivateEndpoint_Connections_Deny-Storage-PEConn/**
          policies/policies/Deny_vNet_peering_Deny-VNet-Peering/**
          policies/policies/Deny_vNet_peering_cross_subscription._Deny-VNET-Peer-Cross-Sub/**
          policies/policies/MySQL_database_servers_enforce_SSL_connections._Deny-MySql-http/**
          policies/policies/Deny_PrivateEndpoint_PrivateLink_Service_Connections_Deny-PE-cross-tenant/**
          policies/policies/PostgreSQL_database_servers_enforce_SSL_connection._Deny-PostgreSql-http/**
          policies/policies/Prevent_cross_subscription_Private_Link_Deny-plink-cross-Sub/**
          policies/policies/Deny_the_creation_of_private_DNS_Deny-Private-DNS-Zones/**
          policies/policies/Public_network_access_should_be_disabled_for_MariaDB_Deny-PublicEndpoint-MariaDB/**
          policies/policies/Deny_the_creation_of_public_IP_Deny-PublicIP/**
          policies/policies/Deny_vNet_peering_Deny-VNet-Peering/**
          policies/policies/Deny_vNet_peering_cross_subscription._Deny-VNET-Peer-Cross-Sub/**
          policies/policies/Deny_Storage_PrivateEndpoint_Connections_Deny-Storage-PEConn/**
          policies/policies/Storage_Account_set_to_minumum_TLS_and_Secure_transfer_should_be_enabled_Deny-Storage-minTLS/**
          policies/policies/SQL_Managed_Instance_should_have_the_minimal_TLS_version_set_to_the_highest_version_Deny-SqlMi-minTLS/**
          policies/policies/Azure_SQL_Database_should_have_the_minimal_TLS_version_set_to_the_highest_version_Deny-Sql-minTLS/**
          policies/policies/Azure_Cache_for_Redis_only_secure_connections_should_be_enabled_Deny-Redis-http/**
          policies/policies/Storage_accounts_should_be_have_minimal_TLS_version_1.2_Deny-storage-tls-lt1-2/**
          policies/policies/Storage_accounts_should_be_have_minimal_TLS_version_1.2_Deny-storage-tls-lt1-2/**
          policies/policies/Azure_SQL_Database_should_have_the_minimal_TLS_version_set_to_the_highest_version_Deny-Sql-minTLS/**
          policies/policies/SQL_Managed_Instance_should_have_the_minimal_TLS_version_set_to_the_highest_version_Deny-SqlMi-minTLS/**
          policies/policies/Storage_Account_set_to_minumum_TLS_and_Secure_transfer_should_be_enabled_Deny-Storage-minTLS/**
          policies/policies/RDP_access_from_the_Internet_should_be_blocked_Deny-RDP-From-Internet/**
          policies/policies/Prevent_cross_subscription_Private_Link_Deny-plink-cross-Sub/**
          policies/policies/MySQL_database_servers_enforce_SSL_connections._Deny-MySql-http/**
          policies/policies/Application_Gateway_should_be_deployed_with_WAF_enabled_Deny-AppGW-Without-WAF/**
          policies/policies/Web_Application_should_only_be_accessible_over_HTTPS_Deny-AppServiceWebApp-http/**
          policies/policies/Function_App_should_only_be_accessible_over_HTTPS_Deny-AppServiceFunctionApp-http/**
          policies/policies/API_App_should_only_be_accessible_over_HTTPS_Deny-AppServiceApiApp-http/**
          policies/policies/Azure_Cache_for_Redis_only_secure_connections_should_be_enabled_Deny-Redis-http/**
          policies/policies/Function_App_should_only_be_accessible_over_HTTPS_Deny-AppServiceFunctionApp-http/**
          policies/policies/API_App_should_only_be_accessible_over_HTTPS_Deny-AppServiceApiApp-http/**
          policies/policies/Web_Application_should_only_be_accessible_over_HTTPS_Deny-AppServiceWebApp-http/**
